### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/YAGO3-10/vocab_e1'

### ISSUE THREAD

**Issue by Chandrahasd** [SmartDataAnalytics/LiteralE#1]
While running the preprocess_num_lit.py, I got this error.
I couldn't find this file in the data folders, nor any script to create this file.
Can you please let me know how can I get this file?

Thanks,
Chandrahas

**Comment by wiseodd** [comment]
Hi, 

Thanks for notifying us the error.
I've added step 3.2 in the readme, i.e. you need to run: `python main_literal.py dataset {FB15k, FB15k-237, YAGO3-10} epochs 0 process True`.

Please let us know if you encounter any other difficulties.

**Comment by zhangzy6** [comment]
I also couldn't find this file in the data folders, nor any script to create this file.And when I run python main_literal.py dataset {FB15k, FB15k-237, YAGO3-10} epochs 0 process True.It occurs another error
