### ISSUE TITLE
when I run python main_literal.py dataset FB15k-237 epochs 0 process True,it always occurs error

### ISSUE THREAD

**Issue by zhangzy6** [SmartDataAnalytics/LiteralE#2]
IOError: Failed to interpret file 'data/FB15k-237/literals/numerical_literals.npy' as a pickle

**Comment by wiseodd** [comment]
Hi, I'm not sure about the error. It works in my Python 3.6 environment:

``` python
In [7]: np.load(f'data/FB15k-237/literals/numerical_literals.npy')
Out[7]:
array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0., 48442.,     0., ...,     0.,     0.,     0.],
       ...,
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]],
      dtype=float32)
```

**Comment by zhangzy6** [comment]
Thank you very much.I have tried many times,but it always  occurs error.So can you give me the processed data set?

**Comment by ReadyTeresa** [comment]
I'm missing numerical_literals.npy of this document. Can you share it with me?

**Comment by MdAsifKhan** [comment]
You can create numerical_literals.npy as follows:

python preprocess_num_lit.py --dataset FB15k
