### ISSUE TITLE
How to reproduce your work? 

### ISSUE THREAD

**Issue by phucty** [SmartDataAnalytics/LiteralE#3]
Thank you for sharing the source code as well as datasets.

I followed your instruction and stuck at the step of 3.ii. 
The error is 
No such file or directory: 'data/FB15k-237/literals/numerical_literals.npy'

There is only a numerical_literals.txt file at this folder. 
I tried to load from txt file and then convert it to numpy array. 
But got an error at the "Normalize numerical literals"
I think your numerical_literals.npy might different from the txt file in this repository. 

Could you please let me know how to reproduce your experiments?

Phuc

**Comment by MdAsifKhan** [comment]
Hey

before step 3.ii) please prepare the numerical literal data as follows:
'python preprocess_num_lit.py --dataset FB15k'

This will create *.npy file

Asif

**Comment by phucty** [comment]
Hi Asif,
Thank you for your response. 

There is only one file numerical_literals.npy created after the command. 

I still get another error of missing file of 
No such file or directory: 'data/FB15k-237/literals/text_literals.npy'

Phuc

**Comment by MdAsifKhan** [comment]
Hey,
For text features we use GloVe embeddings from Spacy. You could use any pretrained text embeddings and save it as a .npy file. Here is an example script to use Spacy:

```python
import numpy as np
import argparse
import pandas as pd
from pathlib import Path
import spacy
import unicodedata

parser = argparse.ArgumentParser(
    description='Create literals'
)
parser.add_argument('--dataset', default='YAGO3-10', metavar='',
                    help='which dataset in {`YAGO3-10`, `FB15k`, `FB15k-237`} to be used? (default: YAGO3-10)')
args = parser.parse_args()


# Load vocab
vocab = np.load(f'{str(Path.home())}/.data/{args.dataset}/vocab_e1')

ent2idx = vocab[0]
idx2ent = vocab[1]

df = pd.read_csv(f'data/{args.dataset}/literals/text_literals.txt', header=None, sep='\t')
nlp = spacy.load('en')

features = np.zeros([len(idx2ent), 384])

i = 0

for ent, txt in zip(df[0].values, df[1].values):
    vec = nlp(txt).vector
    idx = ent2idx[unicodedata.normalize('NFC', ent)]
    features[idx, :] = vec

# Save features
print('Saving text features of size {}'.format(features.shape))
np.save(f'data/{args.dataset}/literals/text_literals.npy', features)
```

**Comment by phucty** [comment]
Dear MdAsifKhan, 
Thank you for your answer,

I runned your sharing code but there are two errors:
1. Which spacy model of English is used? There are 6 models on there web site: https://spacy.io/models/en, but it seems that the embedding dimension for a word is around 300 (not 384 in your code). 

2. I changed the dimension to the correct one. Then, I got another problem of getting incorrect id index of this line of code. 
idx = ent2idx[unicodedata.normalize('NFC', ent)]

It seems there are some people got the same issues like me. (Other issues)
Could you please check your code and update your instruction on how to reproduce your work on Readme file? 

Thank you very much.
Best
Phuc

**Comment by wiseodd** [comment]
Hi @phucty,

sorry for very late reply. We have updated the README and put together the missing pieces. Now, our code should be straightforward to run. Please try it out and let us know whether it works for you now.
